version: '2'
services:
  mongo: 
    image: "mongo:3.0"
    ports:
      - "27017:27017"
  rmq:
    image: "rabbitmq:3"
    ports: 
      - "5672:5672"
  web:
    build: .
    ports: 
      - "8080:8080"